#!/bin/bash

# init submodules
echo -e "setting up submodules\n"
git submodule init
git submodule update --recursive

# symlink dotfiles
echo -e "symlinking dotfiles\n"
dotdir=$PWD
sources=("$dotdir/zshrc" "$dotdir/vimrc" "$dotdir/tmux.conf" "$dotdir/profile" "$dotdir/zsh/antigen" "$dotdir/vim" "$dotdir/i3" "$dotdir/polybar")
destinations=("$HOME/.zshrc" "$HOME/.vimrc" "$HOME/.tmux.conf" "$HOME/.profile" "$HOME/.antigen" "$HOME/.vim" "$HOME/.config/i3" "$HOME/.config/polybar")
ammount=${#sources[@]}

for (( i=0; i<${ammount}; i++ ));
do
	src=${sources[$i]}
	dst=${destinations[$i]}
  echo "$src -> $dst"

	if [[ -h $dst ]]; then
		echo -e "$dst is already a link, recreating the link\n"
		rm -f $dst
		ln -s $src $dst

	elif [[ -e $dst ]]; then
		echo -e "$dst exists, backing up and creating a link\n"
		backuptime=$(date +%Y.%m.%d-%H.%M.%S)
		backupdir="$dotdir/backup/$backuptime"
		mkdir -p $backupdir
		mv $dst $backupdir

		ln -s $src $dst

	else
		echo -e "$dst doesn't exist, creating link\n"
		ln -s $src $dst
	fi
done

# install vim plugins
echo "installing vim plugins..."
vim +PluginInstall +qall
echo "done."
