#!/bin/zsh
tmuxinator list | tail -n +2 | tr -s ' ' '\n' \
  | awk '{printf "\"%s\" %s \"run-shell #tmuxinator start %s#\" ", $1, NR, $1}' \
  | sed "s/#/'/g" \
  | xargs tmux display-menu -T " Open Project " 

