-- https://github.com/lukas-reineke/indent-blankline.nvim
-- return {
---@module "ibl"
---@type ibl.config
-- "lukas-reineke/indent-blankline.nvim",
-- dependencies = { "nvim-treesitter/nvim-treesitter" },
-- main = "ibl",
-- opts = {},
-- config = function()
-- 	local highlight = {
-- 		"CursorColumn",
-- 		"Whitespace",
-- 	}
-- 	require("ibl").setup({
-- 		indent = {
-- 			char = "▏",
-- 		},
--
-- 		whitespace = {
-- 			highlight = highlight,
-- 			remove_blankline_trail = false,
-- 		},
-- 	})
--end,
--}
--
return {}
